### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lethanhan97** [rokborf/natural-drag-animation-rbdnd#12]
Thank you for the brilliant package. Would like to request adding typescript support as `@types/natural-drag-animation-rbdnd` currently doesnt exist.

Thank you so much!

**Comment by prajwalkulkarni** [comment]
Hello @rokborf, have there been any updates about this? If not, I'd like to take this up.

**Comment by rokborf** [comment]
Hello @prajwalkulkarni 
No updates, PR is welcomed

**Comment by prajwalkulkarni** [comment]
Cool, working on it,

**Comment by prajwalkulkarni** [comment]
I'm working on getting the types ready to add it to `Definitely typed` repo and will submit a PR there shortly.

**Comment by rokborf** [comment]
Thanks, @prajwalkulkarni
`@types/natural-drag-animation-rbdnd` is available
