### ISSUE TITLE
compatability with version 10

### ISSUE THREAD

**Issue by alexreardon** [rokborf/natural-drag-animation-rbdnd#2]
Hey @rokborf!

We are only a few weeks off version 10 of `react-beautiful-dnd`. The only that that should be relevant for this library is how we do drop animations. We are now doing them with css rather than `react-motion`. You can use the new `dropAnimation` object in the `DraggableStateSnapshot` to retrieve information about a drop animation.

We already have an alpha release: 

`react-beautiful-dnd-next@10.0.0-alpha.2`

**Comment by rokborf** [comment]
Hi @alexreardon !

Thank you for the heads-up. I'll prepare next compatible version to your release.

**Comment by rokborf** [comment]
the new version is ready for release

**Comment by rokborf** [comment]
compatible version 2 is released

**Comment by alexreardon** [comment]
👍👍
