### ISSUE TITLE
Updating sigmoid function or passing in a sigmoid function prop

### ISSUE THREAD

**Issue by DarrenZLew** [rokborf/natural-drag-animation-rbdnd#5]
Thanks for the addon. It works wonderfully except for one small annoyance with the dragged item doing some slight tremors if you barely drag the item.

Curious if you'd be open for a PR to either update the sigmoid function to make the dragged item smoother at smaller movements or to allow a user to pass in a sigmoid function prop instead.

**Comment by dmitrijl-nex** [comment]
Hi Darren,

Yes, PR's are welcome. I think we should do both, but it should not have tremor by default, so it's a more preferred solution

**Comment by rokborf** [comment]
Hi Darren,

Yes, PR's are welcome. I think we should do both, but it should not have tremor by default, so it's a more preferred solution

**Comment by DarrenZLew** [comment]
Sounds good. I can create one.

**Comment by DarrenZLew** [comment]
I have a branch that could be created into a PR, but don't seem to have access to the repo.

**Comment by rokborf** [comment]
You should create a fork and make PR from the fork to this repo.

**Comment by rokborf** [comment]
Added to 2.1.0 version
